FROM node:20-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de definición de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente al contenedor
COPY . .

# Expone el puerto en el que correrá la aplicación Express (e.g., 3000)
EXPOSE 3000

# Comando para iniciar la aplicación
CMD [ "npm", "start" ]